{
    "type": "bundle",
    "id": "bundle--16694af1-757b-42e4-9627-e0b495ad3e54",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--fb62b34b-99ba-4d3a-b7f2-67aa45aa9d1d",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-09-21T00:20:08.327411Z",
            "modified": "2021-09-21T00:20:08.327411Z",
            "name": "CVE-2021-32285",
            "description": "An issue was discovered in gravity through 0.8.1. A NULL pointer dereference exists in the function list_iterator_next() located in gravity_core.c. It allows an attacker to cause Denial of Service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2021-32285"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}