{
    "type": "bundle",
    "id": "bundle--f1a2cda7-3437-4da4-93b0-a1a7a74b3dd2",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--aa1990ab-9b5f-49af-84a9-e5ef29487150",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-08-16T00:24:46.228122Z",
            "modified": "2023-08-16T00:24:46.228122Z",
            "name": "CVE-2023-39661",
            "description": "An issue in pandas-ai v.0.9.1 and before allows a remote attacker to execute arbitrary code via the _is_jailbreak function.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-39661"
                }
            ]
        }
    ]
}